name: Terraform plan

on:
  push:
    branches:
      - main

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
      - name: Terraform validate
        id: validate
        run: terraform validate -no-color